{
 "title": "Statistics",
 "description": "Dishy Statistics",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_INFLUXDB", "label": "InfluxDB DataSource", "query": "starlinkstats" },
   {
    "name": "TBL_STATS",
    "label": "Table name for Statistics",
    "query": "spacex.starlink.user_terminal.status"
   }
  ]
 },
 "panels": [
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "measurement": "spacex.starlink.user_terminal.history",
     "select": [
      [
       { "params": [ "downlink_throughput_bps" ], "type": "field" }
      ],
      [
       { "params": [ "uplink_throughput_bps" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "SNR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "spacex.starlink.user_terminal.history",
     "select": [
      [
       { "params": [ "snr" ], "type": "field" },
       { "params": [ " *10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "spacex.starlink.user_terminal.status",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Valid S",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "spacex.starlink.user_terminal.status",
     "select": [
      [
       { "params": [ "valid_s" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ping",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "spacex.starlink.user_terminal.history",
     "select": [
      [
       { "params": [ "pop_ping_latency_ms" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Download",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "spacex.starlink.user_terminal.history",
     "select": [
      [
       { "params": [ "downlink_throughput_bps" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upload",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "spacex.starlink.user_terminal.history",
     "select": [
      [
       { "params": [ "uplink_throughput_bps" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latency & Drop Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "measurement": "spacex.starlink.user_terminal.history",
     "select": [
      [
       { "params": [ "pop_ping_latency_ms" ], "type": "field" }
      ],
      [
       { "params": [ "pop_ping_drop_rate" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Obstructed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "measurement": "spacex.starlink.user_terminal.history",
     "select": [
      [
       { "params": [ "fraction_obstructed" ], "type": "field" },
       { "params": [ "*100" ], "type": "math" }
      ]
     ]
    },
    {
     "measurement": "spacex.starlink.user_terminal.status",
     "select": [
      [
       { "params": [ "fraction_obstructed" ], "type": "field" },
       { "params": [ "*100" ], "type": "math" },
       { "params": [ "Percent Obstructed" ], "type": "alias" }
      ],
      [
       { "params": [ "seconds_obstructed" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "System Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "measurement": "spacex.starlink.user_terminal.status",
     "query": "SELECT \"currently_obstructed\" AS \"Obstructed\", \"alert_unexpected_location\" AS \"Wrong Location\", \"alert_thermal_throttle\" AS \"Thermal Throttle\", \"alert_thermal_shutdown\" AS \"Thermal Shutdown\", \"alert_motors_stuck\" AS \"Motors Stuck\", \"state\" AS \"State\" FROM \"spacex.starlink.user_terminal.status\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       { "params": [ "State" ], "type": "alias" }
      ],
      [
       { "params": [ "currently_obstructed" ], "type": "field" },
       { "params": [ "Obstructed" ], "type": "alias" }
      ],
      [
       { "params": [ "alert_unexpected_location" ], "type": "field" },
       { "params": [ "Bad Location" ], "type": "alias" }
      ],
      [
       { "params": [ "alert_thermal_throttle" ], "type": "field" },
       { "params": [ "Temp Throttled" ], "type": "alias" }
      ],
      [
       { "params": [ "alert_thermal_shutdown" ], "type": "field" },
       { "params": [ "Temp Shutdown" ], "type": "alias" }
      ],
      [
       { "params": [ "alert_motors_stuck" ], "type": "field" },
       { "params": [ "Motors Stuck" ], "type": "alias" }
      ],
      [
       { "params": [ "software_version" ], "type": "field" },
       { "params": [ "Software Version" ], "type": "alias" }
      ],
      [
       { "params": [ "alert_slow_ethernet_speeds" ], "type": "field" },
       { "params": [ "Slow Speed" ], "type": "alias" }
      ],
      [
       { "params": [ "alert_mast_not_near_vertical" ], "type": "field" },
       { "params": [ "Mast Not Vertical" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}