{
 "title": "Network Statistics",
 "description": "Network Statistics",
 "tags": [
  "networking",
  "monitoring",
  "telegraf",
  "influxdb",
  "isp"
 ],
 "time": { "from": "now/d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "PingURL",
    "query": "SHOW TAG VALUES FROM \"ping\" WITH KEY = \"url\""
   }
  ]
 },
 "panels": [
  { "title": "Speedtest", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ping",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "ping_latency" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Download Speed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "download_bandwidth" ], "type": "field" },
       { "params": [ " / 125000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transmit/Receive",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "alias": "Download",
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "download_bandwidth" ], "type": "field" },
       { "params": [ " / 125000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Upload",
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "upload_bandwidth" ], "type": "field" },
       { "params": [ " / 125000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ping AVG response time",
   "type": "gauge",
   "description": "Average response time for External Ping in ms.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "ping",
     "query": "SELECT \"average_response_ms\" FROM \"ping\" ",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$PingURL$/" }
     ]
    }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "upload_bandwidth" ], "type": "field" },
       { "params": [ " / 125000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Download/Upload",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "Download",
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "download_bytes" ], "type": "field" },
       { "params": [ " / 125000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Upload",
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "upload_bytes" ], "type": "field" },
       { "params": [ " / 125000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  { "title": "DNS/ICMP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "DNS AVG Query time",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_domain",
     "groupBy": [
      { "params": [ "domain" ], "type": "tag" }
     ],
     "measurement": "dns_query",
     "select": [
      [
       { "params": [ "query_time_ms" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "ICMP average response",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "url" ], "type": "tag" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$PingURL$/" }
     ]
    }
   ]
  },
  {
   "title": "ICMP Packet loss (%)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "percent_packet_loss" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ICMP Analysis",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "ICMP Out redirects",
     "measurement": "net",
     "select": [
      [
       { "params": [ "icmp_outredirects" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "ICMP In Redirects",
     "measurement": "net",
     "select": [
      [
       { "params": [ "icmp_inredirects" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "ICMP Out Time exceeded",
     "measurement": "net",
     "select": [
      [
       { "params": [ "icmp_outtimeexcds" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "ICMP In Time exceeded",
     "measurement": "net",
     "select": [
      [
       { "params": [ "icmp_intimeexcds" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jitter (ICMP/HTTP)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "HTTP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "http_response",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" },
       {
        "params": [],
        "type": "stddev"
       }
      ]
     ]
    },
    {
     "alias": "ICMP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "standard_deviation_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Internet Connectivity Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "$PingURL Ping",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 24 },
   "repeat": "PingURL",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"average_response_ms\") FROM \"ping\" WHERE (\"url\" =~ /^$PingURL$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Host Download",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP GET response time (ms)",
   "type": "timeseries",
   "description": "HTTP GET request response time (ms)",
   "gridPos": { "h": 8, "w": 11, "x": 4, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "server" ], "type": "tag" }
     ],
     "measurement": "http_response",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "method", "operator": "=", "value": "GET" }
     ]
    }
   ]
  },
  {
   "title": "Interface Tx/Rx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Transmit",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Receive",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Drop In",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Drop Out",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "drop_out" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Error In",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "err_in" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Error Out",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "err_out" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Host Upload",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "$PingURL Ping",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 36 },
   "repeat": "PingURL",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 100 - mean(\"percent_packet_loss\") FROM \"ping\" WHERE \"url\" =~ /^$PingURL$/ AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Additional Test Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Netstat Details",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "netstat",
       "query": "SELECT mean(\"tcp_close\") AS \"tcp_close\", mean(\"tcp_close_wait\") AS \"tcp_close_wait\", mean(\"tcp_closing\") AS \"tcp_colsing\", mean(\"tcp_fin_wait1\") AS \"tcp_fin_wait1\", mean(\"tcp_fin_wait2\") AS \"tcp_fin_wait2\", mean(\"tcp_last_ack\") AS \"tcp_last_ack\", mean(\"tcp_syn_recv\") AS \"tcp_syn_recv\", mean(\"tcp_syn_sent\") AS \"tcp_syn_sent\", mean(\"tcp_listen\") AS \"tcp_listen\", mean(\"tcp_time_wait\") AS \"tcp_time_wait\", mean(\"udp_socket\") AS \"udp_socket\", mean(\"tcp_established\") AS \"tcp_established\" FROM \"netstat\" GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "tcp_close" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "tcp_close" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$NetHost$/" }
       ]
      }
     ]
    },
    {
     "title": "HTTP response codes",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_server",
       "groupBy": [
        { "params": [ "server" ], "type": "tag" },
        { "params": [ "method" ], "type": "tag" }
       ],
       "measurement": "http_response",
       "select": [
        [
         { "params": [ "http_response_code" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Speedtest Details",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "measurement": "speedtest",
       "select": [
        [
         { "params": [ "server_name" ], "type": "field" },
         { "params": [ "Server Name" ], "type": "alias" }
        ],
        [
         { "params": [ "server_location" ], "type": "field" },
         { "params": [ "Server Location" ], "type": "alias" }
        ],
        [
         { "params": [ "interface_externalIp" ], "type": "field" },
         { "params": [ "External IP" ], "type": "alias" }
        ],
        [
         { "params": [ "result_url" ], "type": "field" },
         { "params": [ "URL" ], "type": "alias" }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}